# tasks file for roles/container/nginx-proxy
---
- name: Create a proxy network
  community.docker.docker_network:
    name: proxy_network
    driver: bridge
    driver_options:
      com.docker.network.bridge.name: "br-{{ service_name }}"
    internal: false

- name: Make sure the nginx-proxy container is created and running
  community.docker.docker_container:
    name: "{{ service_name }}"
    image: "nginxproxy/nginx-proxy"
    recreate: "{{ allow_recreate_containers | default('false') }}"
    keep_volumes: true
    restart_policy: unless-stopped
    networks:
      - name: proxy_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "{{ service_data_location }}/conf.d:/etc/nginx/conf.d"
      - "{{ service_data_location }}/certs:/etc/nginx/certs"
      - "{{ service_data_location }}/vhost.d:/etc/nginx/vhost.d"
      - "{{ service_data_location }}/html:/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"

- name: Make sure the acme-companion container is created and running
  community.docker.docker_container:
    name: "{{ service_name }}-acme"
    image: "nginxproxy/acme-companion"
    recreate: "{{ allow_recreate_containers | default('false') }}"
    keep_volumes: true
    restart_policy: unless-stopped
    env:
      DEFAULT_EMAIL: "{{ acme_admin_email }}"
      NGINX_PROXY_CONTAINER: "{{ service_name }}"
    volumes:
      - "{{ service_data_location }}/conf.d:/etc/nginx/conf.d"
      - "{{ service_data_location }}/certs:/etc/nginx/certs"
      - "{{ service_data_location }}/vhost.d:/etc/nginx/vhost.d"
      - "{{ service_data_location }}/html:/usr/share/nginx/html"
      - "{{ service_data_location }}/acme:/etc/acme.sh"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

- name: Make sure the self-signed-proxy-companion container is created and running
  community.docker.docker_container:
    name: "{{ service_name }}-self-signed-companion"
    image: sebastienheyd/self-signed-proxy-companion
    recreate: "{{ allow_recreate_containers | default('false') }}"
    keep_volumes: true
    restart_policy: unless-stopped
    env:
      NGINX_PROXY_CONTAINER: "{{ service_name }}"
    volumes:
      - "{{ service_data_location }}/certs:/etc/nginx/certs"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

- name: Copy custom config files to nginx conf.d directory
  ansible.builtin.template:
    src: "proxy_defaults.conf.j2"
    dest: "{{ service_data_location }}/conf.d/proxy_defaults.conf"
  notify:
    - Restart nginx-proxy container

- name: Get all running containers
  ansible.builtin.command: docker ps --format "{{ '{{' }} .Names {{ '}}' }}"
  register: all_containers

- name: Add containers and configure vhosts with custom settings
  ansible.builtin.include_tasks: configure_containers.yml
  loop: "{{ all_containers.stdout_lines }}"
  loop_control:
    loop_var: container